name: Playwright Tests

on:
  push:
    branches: [ main, master, practice ]

  pull_request:
    branches: [ main, master, practice ]

  # Runs every day at 09:00 AM IST
  schedule:
    - cron: '0 9 * * *'
      timezone: 'Asia/Kolkata'

  # Allows manual execution
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30